title: Son Tung BUI
logo: assests/images/anhthe-modified.png
description: AI Engineer / Data Scientist

# Social Media
social:
  - icon: fa-linkedin
    url: https://www.linkedin.com/in/sontung2310/
  - icon: fa-github
    url: https://github.com/sontung2310
  - icon: fa-envelope
    url: mailto:buisontung2310@gmail.com
  
show_social: true
theme: jekyll-theme-minimal